title = "JCast"
baseURL = "https://jcast.dev"
languageCode = "nl-be"
defaultContentLanguage = "nl"
enableRobotsTXT = true

[pagination]
pagerSize = 10

[params]
description = "De podcast over IT, dev life, soft skills en gezonde meningsverschillen."
author = "Oumaima Zerouali, Viktor Van Steenweghen & Maarten Casteels"
keywords = "Nederlandstalige podcast, Belgische podcast, tech podcast, Java podcast, software development podcast, IT podcast België, developer podcast, programmeren, clean code, agile"
ogImage = "/images/logo-without-bg.png"

[params.podcast.platforms]
spotify = "https://open.spotify.com/show/3wfdG6IjCoJjfEx33MsM2W"
apple = "https://podcasts.apple.com/podcast/jcast/id1814550001"
amazon = "https://music.amazon.com/podcasts/bcbbf086-31fc-4cc5-b497-cbd9600ae48f"
itunes = "https://pca.st/itunes/1814550001"
podcastaddict = "https://podcastaddict.com/podcast/jcast/5881797"
deezer = "https://www.deezer.com/show/1001888441"
playerfm = "https://player.fm/series/series-3665934"

[params.assets]
customCSS = ["css/styles.css"]

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
